#include <iostream>

struct X {
  char member;
};

int main() {
  X x1;                 // default ctor
  X x2{x1};             // copy ctor
  // std::move introduced in C++11
  X x3{std::move(x2)};  // move ctor
  // With round parentheses, error! With {}, no problem!
  X x4{};               // default ctor calling {} to each member
  x4 = x3;              // copy assignment
  X x5;                 // default ctor
  x5 = std::move(x4);   // move assignment

  // Output: random char (that is stored in the allocated memory slot)
  std::cout << x5.member << std::endl;  // what do you expect??

  // Take home: A bunch of functions (the above ones) are automatically 
  // generated by the compiler (if not defined explicitly).
  return 0;
}
